@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iDiamondhunter.morebows.entities;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;
